// @author: Nathaly Alarcon
// Javascript code using VueJS


vm = new Vue({
      el: 'body',
      data: {
        message: '',
        testNathaly : 'Si veo funciona',
        bio : ''
    },
    ready: function () {
        this.getTorreProfileFromVar();
    },
    methods: {
        getTorreProfileFromVar : function() {
            // Here I've used the values from the file data.js because I was not able to connect to Torre Api
            this.bio = torreBio;
        },


        fetchProfile: function () {
            // Trying to get the profile using vue-components...
            // It did not work
            profileUrl = 'https://bio.torre.co/nathalyalarcont.json';
            header =  {"X-Auth-Token": "1-cd98917d1314d8c182263c136dfef5326d5693d2-1-EsVuA8ExTr2TVCNwRBtUlS9U2NxDu+LrKdG6oltBrlpU7sghXl/ayEfJMZg3WkLee+xCVj+p/x2YtDBTKz46E03j54RgbE/AwrWO3Td3tRTbtTdyLDiHTd8SPAfCu2AvsUQ2T6RkMz/sm54kUe30s9y9zKpzQC4jNGkbZGmgh3qXfNNVWZnFVuOle+wNWd5GKVbtb2NR766ZEAeAP6nmA3RwVzuSI1+5z4RihGrw5nY6dQuEhK3lLvNqX0YUFSnAWpKD1wDlO4gu2S6KXT2cyOWfEOd3fbMPQQb6Uji3+XkI2fTlHaGTmnxNPaM4GTl7dMzxVMmdJ7yvTF1MbyZdpJNAaO+IvqEwWiXl8tuD7cFaFj2Ckn9BvZZ3FGsOoqvRdSbjYuMfuMAIY+XmelpymN1A/nNUgKVQMqrAyY+ABIH2giYYDB9WYsmuqdUi5DPt4mdSPI9R/yW61UPiuBvl5qI1mc9tkRPIAT98Cf+aH0r+uc7NbCXopYIErUxzcEfSbYd46jf/95D3ZEX6HZtBb9Ept6c1gQZqfjicMWfun1wn6Z0ze6ckHwZQVZPA0C/velGhwRFVejuw0BeHgYE7ViL23IeG5sb4uirroK+O1hpPhCjcEJ/Mj96OyKQ1KwnYVGFaRcTHArWQB8PUmKazVrtPhxB0Zv3sfIIORP8="};
            this.$http.get('https://bio.torre.co/api/bios/nathalyalarcont/achievements', {'header' : header})
            .then(function (response) {
                        // set data
                        vm.$set('profile', response.data);
                        alert(JSON.stingify(profile));
                    });
        },
        getTorreProfileAPI: function(){
            // Trying to get the profile using jquery...
            // Here I've used the code generated by postman.
            // It did not work

            url = 'https://bio.torre.co/api/bios/nathalyalarcont/achievements';
            header =  {"X-Auth-Token": "1-cd98917d1314d8c182263c136dfef5326d5693d2-1-EsVuA8ExTr2TVCNwRBtUlS9U2NxDu+LrKdG6oltBrlpU7sghXl/ayEfJMZg3WkLee+xCVj+p/x2YtDBTKz46E03j54RgbE/AwrWO3Td3tRTbtTdyLDiHTd8SPAfCu2AvsUQ2T6RkMz/sm54kUe30s9y9zKpzQC4jNGkbZGmgh3qXfNNVWZnFVuOle+wNWd5GKVbtb2NR766ZEAeAP6nmA3RwVzuSI1+5z4RihGrw5nY6dQuEhK3lLvNqX0YUFSnAWpKD1wDlO4gu2S6KXT2cyOWfEOd3fbMPQQb6Uji3+XkI2fTlHaGTmnxNPaM4GTl7dMzxVMmdJ7yvTF1MbyZdpJNAaO+IvqEwWiXl8tuD7cFaFj2Ckn9BvZZ3FGsOoqvRdSbjYuMfuMAIY+XmelpymN1A/nNUgKVQMqrAyY+ABIH2giYYDB9WYsmuqdUi5DPt4mdSPI9R/yW61UPiuBvl5qI1mc9tkRPIAT98Cf+aH0r+uc7NbCXopYIErUxzcEfSbYd46jf/95D3ZEX6HZtBb9Ept6c1gQZqfjicMWfun1wn6Z0ze6ckHwZQVZPA0C/velGhwRFVejuw0BeHgYE7ViL23IeG5sb4uirroK+O1hpPhCjcEJ/Mj96OyKQ1KwnYVGFaRcTHArWQB8PUmKazVrtPhxB0Zv3sfIIORP8="};

            // $.get({'url': url, 'headers': header, function(data){ 
            //     stories = data;
            // }});

            // url = 'https://torreco.github.io/people/2517'

            // $.ajax({
            //     url: url,
            //     type: 'GET',
            //     dataType: 'json',
            //     headers: header,
            //     // contentType: 'application/json; charset=utf-8',
            //     success: function (result) {
            //        // CallBack(result);
            //     },
            //     error: function (error) {

            //     }
            // });
        
            var settings = {
              "async": true,
              "crossDomain": true,
              "url": "https://bio.torre.co/api/bios/nathalyalarcont",
              "method": "GET",
              "headers": {
                "x-auth-token": "1-cd98917d1314d8c182263c136dfef5326d5693d2-1-EsVuA8ExTr2TVCNwRBtUlS9U2NxDu+LrKdG6oltBrlpU7sghXl/ayEfJMZg3WkLee+xCVj+p/x2YtDBTKz46E03j54RgbE/AwrWO3Td3tRTbtTdyLDiHTd8SPAfCu2AvsUQ2T6RkMz/sm54kUe30s9y9zKpzQC4jNGkbZGmgh3qXfNNVWZnFVuOle+wNWd5GKVbtb2NR766ZEAeAP6nmA3RwVzuSI1+5z4RihGrw5nY6dQuEhK3lLvNqX0YUFSnAWpKD1wDlO4gu2S6KXT2cyOWfEOd3fbMPQQb6Uji3+XkI2fTlHaGTmnxNPaM4GTl7dMzxVMmdJ7yvTF1MbyZdpJNAaO+IvqEwWiXl8tuD7cFaFj2Ckn9BvZZ3FGsOoqvRdSbjYuMfuMAIY+XmelpymN1A/nNUgKVQMqrAyY+ABIH2giYYDB9WYsmuqdUi5DPt4mdSPI9R/yW61UPiuBvl5qI1mc9tkRPIAT98Cf+aH0r+uc7NbCXopYIErUxzcEfSbYd46jf/95D3ZEX6HZtBb9Ept6c1gQZqfjicMWfun1wn6Z0ze6ckHwZQVZPA0C/velGhwRFVejuw0BeHgYE7ViL23IeG5sb4uirroK+O1hpPhCjcEJ/Mj96OyKQ1KwnYVGFaRcTHArWQB8PUmKazVrtPhxB0Zv3sfIIORP8=",
                "authorization": "Basic YTph",
                // "cache-control": "no-cache",
                // "postman-token": "6746cbd9-f689-c23d-890a-2527914a77a1",
               // 'Access-Control-Allow-Origin' : "http://localhost:8089",
               'dataType': 'json',
               'format': 'json',   
               'origin' : '*'
                }
            }

            $.ajax(settings).done(function (response) {
                console.log(response);
            });
        }     

}
});




// Linkedin Functions
// Runs when the JavaScript framework is loaded
function onLinkedInLoad() {
    IN.Event.on(IN, "auth", OnLinkedInAuth);
}


// Runs when the viewer has authenticated
function onLinkedInAuth() {
    IN.API.Profile("me").fields("id","first-name", "last-name", "email-address").result(displayProfiles);
}

// 2. Runs when the Profile() API call returns successfully
function displayProfiles(profiles) {
    member = profiles.values[0];
    document.getElementById("profiles").innerHTML = 
    "<p>"+member.id+"<br> " +  member.firstName + "<br> " + member.lastName + "<br>"+member.emailAddress+"</p>";
}

function OnLinkedInAuth() {  
    IN.API.Profile("me").result(ShowProfileData);  
}  

function ShowProfileData(profiles) {  
    var member = profiles.values[0];  

    var id = member.id;  
    var firstName = member.firstName;  
    var lastName = member.lastName;  
    var photo = member.pictureUrl;  
    var headline = member.headline;  
        //use information captured above  
        var stringToBind = "<p>First Name: " + firstName + " <p/><p> Last Name: " + lastName + "<p/><p>User ID: " + id + " and Head Line Provided: " + headline + "<p/>" + "<pre>" + JSON.stringify(profiles)+ "</pre>";  
        document.getElementById('profiles').innerHTML = stringToBind;  
}


